# Generated by Django 3.0 on 2022-11-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0002_auto_20221116_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
