# Generated by Django 3.0 on 2022-11-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0003_auto_20221116_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='name',
            field=models.CharField(blank=True, default='kissa', max_length=50, null=True),
        ),
    ]
